[web]
web-server ansible_host="13.234.37.208" #<WEB_PUBLIC_IP>

[database]
db-server ansible_host="10.20.2.110" #<MONGODB_PRIVATE_IP>

[database:vars]
ansible_ssh_common_args='-o ProxyJump=ubuntu@13.234.37.208 -o IdentityFile=~/.ssh/travel-key.pem' #<WEB_PUBLIC_IP>
